# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

env:
  REGISTRY_NAME: "4226624vylk4uwthreg.azurecr.io"
  REPOSITORY_NAME: "wth/dotnetcoreapp"
  DOCKER_FOLDER_PATH: "Application/src/RazorPagesTestSample"
  TAG: ${{ github.run_number }}

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Application/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Application/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build --no-restore Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login ${{env.REGISTRY_NAME}} -u ${{secrets.ACR_USERNAME}} -p ${{secrets.ACR_PASSWORD}}
    - name: Docker build
      run: docker build -t ${{env.REGISTRY_NAME}}/${{env.REPOSITORY_NAME}}:${{env.TAG}} --build-arg build_version=${{env.TAG}} ${{env.DOCKER_FOLDER_PATH}}
    - name: Docker push
      run: docker push ${{env.REGISTRY_NAME}}/${{env.REPOSITORY_NAME}}:${{env.TAG}}

  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Update Web App
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 4226624vylk4u-dev
        images: ${{secrets.ACR_LOGIN_SERVER}}/${{env.REGISTRY_NAME}}:${{env.TAG}}

